name = "somalia_news_nextjs"
compatibility_date = "2024-09-23"

[[d1_databases]]
binding = "DB" # Keep D1 binding for Pages Functions
database_name = "somalia_news_db"
preview_database_id = "somalia_news_db" # Add preview_database_id for local development/preview

[env.production.d1_databases]
binding = "DB"
database_name = "somalia_news_db_prod"
database_id = "a5c443bd-4c8e-4c06-89c6-4a15959662a7"
