name = "somalia_news_nextjs"
compatibility_date = "2024-09-23"

type = "python"

[build]
# Command to install dependencies and run your main script
command = "pip install -r requirements.txt && python worker.py"  # Ensure 'worker.py' is your script
cwd = "."
watch_dir = "."

[assets]
directory = ".open-next/assets"
binding = "ASSETS"

[[d1_databases]]
binding = "DB"
database_name = "somalia_news_db"

[env.production.d1_databases]
binding = "DB"
database_name = "somalia_news_db_prod"
database_id = "a5c443bd-4c8e-4c06-89c6-4a15959662a7"
