#:schema node_modules/wrangler/config-schema.json
name = "somalia_news_nextjs"
main = ".open-next/worker.js"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]

[build]
command = "npm run build"
cwd = "."
watch_dir = "."

[assets]
directory = ".open-next/assets"
binding = "ASSETS"

[[d1_databases]]
binding = "DB"
database_name = "somalia_news_db"
# database_id = "" # for local dev
# preview_database_id = "" # optional for previews

[env.production.d1_databases]
binding = "DB"
database_name = "somalia_news_db_prod"
database_id = "a5c443bd-4c8e-4c06-89c6-4a15959662a7"
