#:schema node_modules/wrangler/config-schema.json
name = "somalia_news_nextjs"
main = ".open-next/worker.js"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]

[assets]
directory = ".open-next/assets"
binding = "ASSETS"

# --- Default / Local Development Database --- 
# Used when running 'wrangler dev'
[[d1_databases]]
binding = "DB" # Environment variable name for the database binding
database_name = "somalia_news_db" # Name for the local database
# database_id = "" # Usually omit for local file-based DB
# preview_database_id = "<YOUR_PREVIEW_DB_ID>" # Optional: If you use preview DBs

# --- Production Database --- 
# Used when deploying to Cloudflare Pages (production)
[env.production.d1_databases]
binding = "DB" # Keep the binding name the same
database_name = "somalia_news_db_prod" # Use the production DB name
database_id = "a5c443bd-4c8e-4c06-89c6-4a15959662a7" # <<< YOUR PRODUCTION DB ID GOES HERE
